spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/triple?characterEncoding=utf8
    username: root
    password: capstone2022


  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true

#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySql



